## 各類資料結構如何轉型

In [1]:
# list v
# tuple v
# dictionary v
# set v
# numpy v
# pandas (dataframe, series) v

# List

## List to tuple

In [42]:
list1 = [1,2,3,3]
list1 

[1, 2, 3, 3]

In [5]:
tuple(list1)

(1, 2, 3)

## List to dictionary

In [6]:
dict1 ={}
for i in range(len(list1)):
    dict1[i] = list1[i]
dict1

{0: 1, 1: 2, 2: 3}

In [43]:
dict2 = dict(enumerate(list1, 0))
dict2

{0: 1, 1: 2, 2: 3, 3: 3}

## List to set

In [9]:
# method 1
# 可以轉型
# 但重複的元素會刪除

set(list1)

{1, 2, 3}

In [11]:
# method 2
# 可以轉型
# 但重複的元素會刪除
m_set = set()
for i in list1:
    m_set.add(i)
m_set

{1, 2, 3}

## List to Numpy

In [12]:
import numpy as np 
numpy_list = np.asarray(list1)
numpy_list

array([1, 2, 3, 3])

## List to pandas (DataFrame)

In [13]:
import pandas as pd

list_dataframe = pd.DataFrame(list1)
list_dataframe

0
0  1
1  2
2  3
3  3

## List to pandas (Series)

In [14]:
list_series = pd.Series(list1)
list_series

0    1
1    2
2    3
3    3
dtype: int64

# tuple

In [45]:
tuple1 = (1,2,3)
tuple1 

(1, 2, 3)

## tuple to List

In [16]:
list(tuple1)

[1, 2, 3]

## tuple to Dictionary

In [19]:
tuple_dictionary  = {}
for i in range(len(tuple1)):
    tuple_dictionary[i] = tuple1[i]
tuple_dictionary

{0: 1, 1: 2, 2: 3}

In [46]:
tuple_dictionary = dict(enumerate(tuple1,0))
tuple_dictionary

{0: 1, 1: 2, 2: 3}

## tuple to set

In [20]:
set(tuple1)

{1, 2, 3}

## tuple to numpy(array)

In [21]:
import numpy as np
tuple_to_numpy = np.array(tuple1)
tuple_to_numpy

array([1, 2, 3])

## Tuple to pandas (DataFrame)

In [22]:
import pandas as pd
Tuple_to_Dataframe = pd.DataFrame(tuple1)
Tuple_to_Dataframe

0
0  1
1  2
2  3

## Tuple to pandas (Series)

In [24]:
import pandas as pd
Tuple_to_Series = pd.Series(tuple1)
Tuple_to_Series

0    1
1    2
2    3
dtype: int64

# Dictionary

## Dictionary to tuple

In [25]:
dict1={1:'1', 2:'2',3:'3'}

tuple(dict1)

(1, 2, 3)

## Dictionary to List

In [26]:
list(dict1)

[1, 2, 3]

## Dictionary to set


In [27]:
set(dict1)

{1, 2, 3}

## Dictionary to Numpy

In [28]:
import numpy as np 
Dictionary_to_numpy = np.array(dict1)
Dictionary_to_numpy 

array({1: '1', 2: '2', 3: '3'}, dtype=object)

## Dictionary to pandas (DataFrame)

In [37]:
import pandas as pd 
#　dict1 取出 values 
#　dict1 取出 keys 
Dictionary_to_Dataframe = pd.DataFrame(dict1.values(), index=dict1.keys())
Dictionary_to_Dataframe 

0
1  1
2  2
3  3

## Dictionary to pandas (Series)

In [38]:
import pandas as pd 
#　dict1 取出 values 
#　dict1 取出 keys 
Dictionary_to_Series = pd.Series(dict1.values(), index=dict1.keys())
Dictionary_to_Series 

1    1
2    2
3    3
dtype: object

# Set

In [4]:
set1 = set([1,2,3,4,5])
set1

{1, 2, 3, 4, 5}

## Set to Dictionary

In [7]:
# 集合是无序的, 不重复的数据类型;
# 因此不支持索引,也不支持切片;也不支持重复;也不支持连接;
# 因此無法將set全部元素加入 dictionary

## Set to tuple

In [8]:
tuple(set1)

(1, 2, 3, 4, 5)

## Set to Numpy

In [9]:
import numpy as np 
Set_to_Numpy = np.array(set1)
Set_to_Numpy

array({1, 2, 3, 4, 5}, dtype=object)

## Set to pandas (DataFrame)


In [10]:
import pandas as pd 
Set_to_pandas1 = pd.DataFrame(set1)
Set_to_pandas1

0
0  1
1  2
2  3
3  4
4  5

## Set to pandas (Series)

In [13]:
Set_to_pandas2 = pd.Series(set1,index=[1,2,3,4,5])
Set_to_pandas2
# TypeError: 'set' type is unordered

TypeError: 'set' type is unordered

# Numpy

In [30]:
import numpy as np 
np_array = np.array([1,2,3,4,5])
np_array

array([1, 2, 3, 4, 5])

## numpy array to list

In [31]:
list(np_array)

[1, 2, 3, 4, 5]

## numpy array to dictionary

In [36]:
# enumerate(sequence, start=1)
# 回傳元素以及元素所在座標
# default: start = 1 回傳座標的起始位置 
numpydictionary= dict(enumerate(np_array.flatten(),1))
numpydictionary   

{1: 1, 2: 2, 3: 3, 4: 4, 5: 5}

In [ ]:
# ndarray.flatten(order='C')
# Return a copy of the array collapsed into one dimension.

## numpy array to tuple

In [37]:
tuple(np_array)

(1, 2, 3, 4, 5)

## numpy array to set

In [38]:
set(np_array)

{1, 2, 3, 4, 5}

## numpy array to Pandas(DataFrame)

In [39]:
array_Dataframe = pd.DataFrame(np_array)
array_Dataframe

0
0  1
1  2
2  3
3  4
4  5

## numpy array to Pandas(Series)

In [40]:
array_series = pd.Series(np_array)
array_series 

0    1
1    2
2    3
3    4
4    5
dtype: int32

# Pandas(DataFrame)

## Pandas(DataFrame) to list

In [3]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1     3
1     2     4

In [50]:
df_tolist = []
for i in range(2):
    df_tolist.append(df.iloc[i][:].to_list())
df_tolist

[[1, 3], [2, 4]]

## Pandas(DataFrame) to set

In [60]:
Dataframe_toset = set()
for i in range(2):
    for j in range(2):
        Dataframe_toset.add(df.iloc[i][j])
Dataframe_toset

{1, 2, 3, 4}

In [24]:
df.loc[:,:]

col1  col2
0     1     3
1     2     4

## Pandas(DataFrame) to tuple

In [26]:
DataFrame_totuple = tuple()
tuple(df.loc[1,:])
# 好像不行

(2, 4)

## Pandas(DataFrame) to dictionary

In [4]:
import pandas as pd 
Dataframe_todictionary = df.to_dict(orient='dict')
Dataframe_todictionary 

{'col1': {0: 1, 1: 2}, 'col2': {0: 3, 1: 4}}

## Pandas(DataFrame) to series

In [8]:
# 應該只能一列一列轉
DataFrame_toseries = pd.Series(df.iloc[0])
DataFrame_toseries

col1    1
col2    3
Name: 0, dtype: int64

# Series

In [10]:
Series = pd.Series([1,2,3,4,5])
Series

0    1
1    2
2    3
3    4
4    5
dtype: int64

## Numpy(Series) to list

In [18]:
Series_tolist = Series.to_list()
Series_tolist

[1, 2, 3, 4, 5]

## Numpy(Series) to set

In [17]:
for i in Series :
    Series_toset.add(i) 
Series_toset

{1, 2, 3, 4, 5}

In [18]:
# 'Series' objects are mutable, thus they cannot be hashed
Series_toset = set()
Series_toset.add(Series)

TypeError: 'Series' objects are mutable, thus they cannot be hashed

## Numpy(Series) to dictionary

In [19]:
Series_todictionary = {}
for i in Series:
    Series_todictionary[i] = i
Series_todictionary   

{1: 1, 2: 2, 3: 3, 4: 4, 5: 5}

In [47]:
Series_todictionary = dict(enumerate(Series,0))
Series_todictionary

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5}

## Numpy(Series) to tuple

In [21]:
Series_totuple = tuple()
tuple(Series)

(1, 2, 3, 4, 5)

## Numpy(Series) to DataFrame

In [28]:
Numpy_toDataFrame = pd.DataFrame(Series)
Numpy_toDataFrame 

0
0  1
1  2
2  3
3  4
4  5